### ISSUE TITLE
mysql_connect has been removed in PHP 7.0.

### ISSUE THREAD

**Issue by klenwell** [wikkawik/WikkaWiki#1230]
See [notice here](http://php.net/manual/en/function.mysql-connect.php).

This issue is anticipated in Issue #171 but acquires some special urgency now because Ubuntu 16 ships with PHP 7.0 by default. I just upgraded my VPS and got killed by the [sanity check here](https://github.com/wikkawik/WikkaWiki/blob/master/wikka.php#L176). This after upgrading to the latest 1.3.7 release.

A temporary fix will be to downgrade the version of PHP on my server or look for the PHP equivalent of something like pyenv. I'll update this ticket once I get a workaround in place.

**Comment by klenwell** [comment]
For a workaround that will downgrade PHP to version 5.6 to circumvent this issue, this [AskUbuntu answer](http://askubuntu.com/a/762161/46766) worked pretty much as advertised:

    sudo apt install software-properties-common
    sudo add-apt-repository ppa:ondrej/php
    sudo apt-get update
    sudo apt-get install php7.0 php5.6 php5.6-mysql php-gettext php5.6-mbstring \
      php-xdebug libapache2-mod-php5.6 libapache2-mod-php7.0
      
    sudo a2dismod php7.0 ; sudo a2enmod php5.6
    sudo service apache2 restart

**Comment by roma0104** [comment]
ArchLinux has also switched to PHP7 and PHP5 is not longer offically supported, though it is available in the AUR.

Seems odd they the changed the command prefix with an 'i' when I gathered that both plugins couldn't run concurrently anyhow.

**Comment by lemire** [comment]
I suggest this gets tagged as a priority.

**Comment by bakoontz** [comment]
@lemire Yes, I agree.  It will be my focus for the next release, hopefully over the holidays.

**Comment by bakoontz** [comment]
Related ticket: #525

**Comment by bakoontz** [comment]
@oemunoz @klenwell OK, I've pushed 1.4.0-pre to the repo for testing.  I need to clean up some errors and other minor things, but it should work under PHP 7.0 (I tested with PHP 7.0.10, MySQL 5.7.14, and Apache 2.4.23).  Please let me know of any major issues.

For those who might be reading this:  DON'T USE THIS IN PRODUCTION!  But do feel free to test.  Note that this branch should still run fine under PHP 5.6 (I tested with 5.6.25).  If you copy this over an existing WikkaWiki install (after making a backup of your WW directory and database of course!), you'll need to switch to PHP 7 *before* attempting to access the site to invoke the auto update.

**Comment by klenwell** [comment]
@bakoontz I've put it on my TODO list. I hope to test a fresh install before end of year. Will update you when complete.

**Comment by oemunoz** [comment]
Hi to all, very good news!!!, I created a docker image with the 1.4.0 [`php 7.0.8 ,mysql 5.7.16 pre-release`, `1.4.0-pre` (*Dockerfile*)](https://github.com/oemunoz/wikkawiki/blob/1.4.0-pre/Dockerfile), 

Check the [documentation](https://github.com/oemunoz/wikkawiki) and run with:
```bash
docker run --rm -it oems/wikkawiki:1.4.0-pre
```

**Comment by oemunoz** [comment]
@bakoontz @klenwell  great code PDO works with SqLite only some changes, I was able to create a version free of mysql It uses only **SqLite**! ! !:

Like usual I build a demo [http://169.46.18.249](http://169.46.18.249), this demo use only SqLite but can use  Mysql again. The docker is on [https://hub.docker.com/r/oems/wikkademo/](https://hub.docker.com/r/oems/wikkademo/) with the tag "1.4.0-pre-md-sqlite". 

This Rocks becose we dont have to keep mysql if is not necesary!!! 

Many tnks, but how I put the SqLite support over table?

**Comment by bakoontz** [comment]
@oemunoz @klenwell That's a pleasant surprise, considering I've never even looked at PDO until I started on this :)  

I still have a few more things to do (error messages, install selection of DB, etc.).  Your pre-md-sqlite branch will be useful, as I want to identify all the DB-specific code and move it out into its own class.  You've done the work for me.

**Comment by oemunoz** [comment]
Hi @bakoontz consider:
[https://github.com/pepitosoft/wikkademo/compare/1.4.0-pre-md...1.4.0-pre-md-sqlite](https://github.com/pepitosoft/wikkademo/compare/1.4.0-pre-md...1.4.0-pre-md-sqlite).

 Maybe is good idea to keep some configurations vars (themes,badwords_path,...)  a put them on a default sqlite database, this can make possibility a better "control panel" from the WEB GUI. But I think you have this on map when choose PDO. 

In other way, I want to open issues for new features, for check for the posiblite for the new release, In this way I can to make a larger messages without saturate the channel.  :-/

tnks

**Comment by bakoontz** [comment]
Go for it. Mark them as "enhancements."

**Comment by klenwell** [comment]
I tested the `1.4.0-pre` version using @oemunoz's [Docker image](https://github.com/oemunoz/wikkawiki/blob/1.4.0-pre/Dockerfile). I ran a basic CRUD test: create, read, update, and delete a page. I noticed two issues along the way:

- Unable to clone pages
- Unable to sort columns in the admin page

I also ran the [Docker image for the 1.3.7 release](https://github.com/oemunoz/wikkawiki/blob/master/Dockerfile) and did not notice these issues.

Thanks, @oemunoz, for putting these Docker images together. It makes basic user testing much more convenient. Still, as these possible regressions show, an automated test suite would be useful, too.

**Comment by klenwell** [comment]
I wanted some more experience with Docker so I built my own image for Wikka 1.4.0:

- https://github.com/klenwell/wikka-docker

I followed @oemunoz's lead but tried to make the [Dockerfile](https://github.com/klenwell/wikka-docker/blob/master/Dockerfile) a little less mysterious to newcomers like myself.

It builds from this LAMP image which I put together after following the [Docker tutorials](https://docs.docker.com/engine/getstarted/) and trying to piece together best practices:

- https://github.com/klenwell/docker-lamps

Comments and corrections are welcome.

**Comment by oemunoz** [comment]
Excellent work @klenwell, I try to write some document ([http://wikkawiki.org/Wikka-Docker](http://wikkawiki.org/Wikka-Docker)) some days ago, but I'm not a good writer either.

The goal of docker is to achieve CI (**Continuous Integration**), I was looking for it after your suggest. 

Maybe If you want, we can build a good DockerFile with **automatic build** from the WikkaWik GitHub repo. I propose to you new issues with enhancement label for:

- Build  a Official Docker on https://hub.docker.com/ (we need a official user @bakoontz) page with the official user. (**automatic build**)
- Some work on CI, some preview with Jenkins, phpunit, selenium for automatic tests. (**Continuous Integration**)

**Comment by bakoontz** [comment]
@oemunoz we used to do "daily builds," but when I moved everything over to github I never had a chance to rescript everything.  This would be an awesome idea, and will play around with the docker stuff when I get some time.

**Comment by lemire** [comment]
@bakoontz 

Things work for me but you may want to remove this line...

https://github.com/wikkawik/WikkaWiki/blob/1.4.0-pre/libs/Database.lib.php#L86

**Comment by lemire** [comment]
@bakoontz Ok. I am getting an issue with 1.4.0-pre...

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'owner' cannot be null in /home/lemire/lemur/html/html/oldWikka/libs/Wakka.class.php:306 Stack trace: #0 /home/lemire/lemur/html/html/oldWikka/libs/Wakka.class.php(306): PDOStatement->execute(Array) #1 /home/lemire/lemur/html/html/oldWikka/libs/Database.lib.php(113): Wakka->Query('\n\t\tINSERT INTO ...', Array) #2 /home/lemire/lemur/html/html/oldWikka/libs/Wakka.class.php(2011): db_addNewRevision(Object(Wakka), Array) #3 /home/lemire/lemur/html/html/oldWikka/handlers/edit/edit.php(142): Wakka->SavePage('SwiftHacking', 'fdfds', '') #4 /home/lemire/lemur/html/html/oldWikka/libs/Wakka.class.php(579): include('/home/lemire/le...') #5 /home/lemire/lemur/html/html/oldWikka/libs/Wakka.class.php(3715): Wakka->IncludeBuffered('edit/edit.php', '', '', 'plugins/handler...') #6 /home/lemire/lemur/html/html/oldWikka/libs/Wakka.class.php(5317): Wakka->Handler('edit') #7 /home/lemire/lemur/html/html/oldWikka/wikka.php(736): Wakka->Run('SwiftHacking', 'edit') #8 {main}
Query: INSERT INTO wikka_pages SET tag = :tag, title = :page_title, time = now(), owner = :owner, user = :user, note = :note, latest = 'Y', body = :bodyarray(6) { [":tag"]=> string(12) "SwiftHacking" [":page_title"]=> string(0) "" [":owner"]=> NULL [":user"]=> string(38) "modemcable092.16-83-70.mc.videotron.ca" [":note"]=> string(0) "" [":body"]=> string(5) "fdfds" } Params: Query failed in Query(): 23000
```

**Comment by lemire** [comment]
@bakoontz 

To fix the problem I had to login as a user before editing the page.

**Comment by bakoontz** [comment]
@lemire Can't reproduce.  I set the SandBox ACLs to be editable by all (*), logged out then edited and saved.  Can you try and reproduce this for me?

**Comment by lemire** [comment]
@bakoontz The problem is reproducible at will on my system, but goes away if I am logged in. Given that I want people to be logged in, this is not a problem for me at this time. However, I am still running code from January. It may very well that this has been fixed. I will report again if the problem persists with a fresh install.

**Comment by emente** [comment]
I can also reproduce the bug lemire (in the comment above me) mentioned. It's still happening with 1.4.0.

It's caused by the wakka->SavePage() function. The $this->existsUser() check inside this function needs an else clause or an default value for $owner as it is possible to pass the empty($owner) check and have $owner still set to null.
